# Generated by Django 4.0.5 on 2022-12-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0004_imagen_imagen_b_jean_imagen_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='calzado',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='camisa',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='campera',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='invernal',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='pantalon',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='remera',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='todo100',
            name='imagen_b',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
