# Generated by Django 4.0.5 on 2022-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0005_calzado_imagen_b_camisa_imagen_b_campera_imagen_b_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50),
        ),
    ]
