# Generated by Django 4.0.5 on 2022-12-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0007_alter_jean_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='genero',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jean',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
