# Generated by Django 4.0.5 on 2022-12-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0008_alter_jean_genero_alter_jean_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
