# Generated by Django 4.0.5 on 2022-12-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_feria', '0009_alter_jean_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jean',
            name='genero',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='jean',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
